[build]
builder = "dockerfile"
dockerfilePath = "morphyverse-server/Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
