[build]
builder = "nixpacks"
buildCommand = "pip install -r morphyverse-server/requirements.txt"

[deploy]
startCommand = "cd morphyverse-server && uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
