import io
import time
from contextlib import asynccontextmanager
from datetime import datetime, timezone

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import StreamingResponse
from PIL import Image, ImageDraw, ImageFont

from config import DEFAULT_CONF
from logger import log_inference
from model.detector import run_detection
from model.loader import get_model, load_model
from store.crop_store import CropStore

crop_store = CropStore()
_startup_ts: str | None = None


@asynccontextmanager
async def lifespan(app: FastAPI):
    global _startup_ts
    load_model()
    _startup_ts = datetime.now(timezone.utc).isoformat()
    yield


app = FastAPI(title="MorphyVerse Inference", lifespan=lifespan)


@app.post("/detect")
async def detect(
    table_id: str = Form(...),
    image: UploadFile = File(...),
    conf: float = Form(DEFAULT_CONF),
):
    try:
        pil_image = Image.open(io.BytesIO(await image.read())).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Cannot decode image")

    crops = crop_store.get_all()
    t0 = time.monotonic()
    detections = run_detection(pil_image, crops, conf)
    latency_ms = int((time.monotonic() - t0) * 1000)

    log_inference(table_id, detections, latency_ms)

    return {
        "detections": detections,
        "latency_ms": latency_ms,
        "embedding_count": crop_store.count(),  # field name kept for Replit compat
        "model_version": "yoloe-26x-seg",
    }


@app.post("/register")
async def register(
    object_id: str = Form(...),  # generated by Replit before calling this endpoint
    object_name: str = Form(...),
    crop: UploadFile = File(...),
):
    if crop.size is not None and crop.size < 32 * 32 * 3:
        raise HTTPException(status_code=400, detail="Crop too small")
    try:
        pil_image = Image.open(io.BytesIO(await crop.read())).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Cannot decode crop image")

    w, h = pil_image.size
    if w < 32 or h < 32:
        raise HTTPException(status_code=400, detail="Crop must be at least 32×32 px")

    crop_store.save(object_id, object_name, pil_image)
    return {"object_id": object_id, "object_name": object_name}


@app.post("/detect/preview", response_class=StreamingResponse)
async def detect_preview(
    image: UploadFile = File(...),
    conf: float = Form(DEFAULT_CONF),
):
    try:
        pil_image = Image.open(io.BytesIO(await image.read())).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Cannot decode image")

    crops = crop_store.get_all()
    detections = run_detection(pil_image, crops, conf)

    draw = ImageDraw.Draw(pil_image)
    try:
        font = ImageFont.truetype("arial.ttf", size=20)
    except OSError:
        font = ImageFont.load_default()

    colors = ["#FF3B30", "#34C759", "#007AFF", "#FF9500", "#AF52DE",
              "#FF2D55", "#5AC8FA", "#FFCC00", "#4CD964", "#FF6B35"]
    name_to_color = {}

    for det in detections:
        color = name_to_color.setdefault(
            det["name"], colors[len(name_to_color) % len(colors)]
        )
        for bbox in det["bboxes"]:
            x1, y1, x2, y2 = bbox
            draw.rectangle([x1, y1, x2, y2], outline=color, width=3)
            label = f"{det['name']} {det['confidence']:.2f}"
            tx, ty = x1 + 4, y1 + 4
            bbox_text = draw.textbbox((tx, ty), label, font=font)
            draw.rectangle(bbox_text, fill=color)
            draw.text((tx, ty), label, fill="white", font=font)

    buf = io.BytesIO()
    pil_image.save(buf, format="JPEG", quality=92)
    buf.seek(0)
    return StreamingResponse(buf, media_type="image/jpeg")


@app.get("/health")
async def health():
    try:
        model = get_model()
        model_loaded = model is not None
    except RuntimeError:
        model_loaded = False

    count = crop_store.count()
    if not model_loaded:
        status = "not_ready"
    elif count == 0:
        status = "degraded"  # model ready but nothing registered yet
    else:
        status = "ok"

    return {
        "status": status,
        "model_loaded": model_loaded,
        "embedding_count": count,      # kept for Replit compat; reflects crop count
        "last_sync_ts": _startup_ts,   # kept for Replit compat; reflects server start
    }
